server.port=8080
#??mybatis?mapper??
mybatis.mapper-locations=classpath:chiku/liu/mapper/*.xml
#??mybatis????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/day?serverTimezone=GMT%2B8&useUnicode=true
spring.datasource.username=root
spring.datasource.password=661960

